# Generated by Django 5.2.17 on 2026-08-22 09:49

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='название')),
                ('is_dapple', models.BooleanField(default=False, verbose_name='дапл (локус M)')),
                ('is_double_dapple', models.BooleanField(default=False, verbose_name='двойной дапл')),
            ],
            options={
                'verbose_name': 'окрас',
                'verbose_name_plural': 'окрасы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='код ISO')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True, verbose_name='код')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('gene', models.CharField(blank=True, max_length=50, verbose_name='ген или локус')),
                ('description', models.TextField(blank=True, verbose_name='описание')),
                ('relevant_coats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('smooth', 'гладкошёрстная'), ('long', 'длинношёрстная'), ('wire', 'жесткошёрстная')], max_length=8), blank=True, default=list, size=None, verbose_name='актуально для шерсти')),
            ],
            options={
                'verbose_name': 'заболевание',
                'verbose_name_plural': 'заболевания',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='идентификатор в легаси')),
                ('provenance', models.CharField(choices=[('imported', 'импортировано из легаси'), ('user', 'внесено пользователем'), ('verified', 'проверено по документам')], default='user', max_length=16, verbose_name='происхождение')),
                ('edited_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None, verbose_name='поля, правленные вручную')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=200, verbose_name='кличка')),
                ('home_name', models.CharField(blank=True, max_length=100, verbose_name='домашняя кличка')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='адрес')),
                ('sex', models.CharField(choices=[('male', 'кобель'), ('female', 'сука'), ('unknown', 'неизвестен')], default='unknown', max_length=8, verbose_name='пол')),
                ('size', models.CharField(blank=True, choices=[('standard', 'стандартная'), ('miniature', 'карликовая'), ('rabbit', 'кроличья')], max_length=10, verbose_name='размер')),
                ('coat', models.CharField(blank=True, choices=[('smooth', 'гладкошёрстная'), ('long', 'длинношёрстная'), ('wire', 'жесткошёрстная')], max_length=8, verbose_name='шерсть')),
                ('color_raw', models.CharField(blank=True, max_length=200, verbose_name='окрас как в легаси')),
                ('date_born', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('date_died', models.DateField(blank=True, null=True, verbose_name='дата смерти')),
                ('date_born_raw', models.CharField(blank=True, max_length=100, verbose_name='дата рождения как в легаси')),
                ('microchip', models.CharField(blank=True, db_index=True, max_length=20, verbose_name='микрочип')),
                ('tattoo', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='клеймо')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='вес, кг')),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='обхват груди, см')),
                ('notes', models.TextField(blank=True, verbose_name='примечания')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedigree.color', verbose_name='окрас')),
                ('dam', models.ForeignKey(blank=True, limit_choices_to={'sex': 'female'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_dam', to='pedigree.dog', verbose_name='мать')),
                ('sire', models.ForeignKey(blank=True, limit_choices_to={'sex': 'male'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring_as_sire', to='pedigree.dog', verbose_name='отец')),
            ],
            options={
                'verbose_name': 'собака',
                'verbose_name_plural': 'собаки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Coi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='COI, %')),
                ('generations', models.PositiveSmallIntegerField(default=10, verbose_name='поколений')),
                ('known_ancestors', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='известно предков, %')),
                ('ancestor_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ancestor loss, %')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='рассчитано')),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coi', to='pedigree.dog')),
            ],
            options={
                'verbose_name': 'коэффициент инбридинга',
                'verbose_name_plural': 'коэффициенты инбридинга',
            },
        ),
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='идентификатор в легаси')),
                ('provenance', models.CharField(choices=[('imported', 'импортировано из легаси'), ('user', 'внесено пользователем'), ('verified', 'проверено по документам')], default='user', max_length=16, verbose_name='происхождение')),
                ('edited_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None, verbose_name='поля, правленные вручную')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='адрес')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedigree.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'питомник',
                'verbose_name_plural': 'питомники',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='kennel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dogs', to='pedigree.kennel', verbose_name='питомник'),
        ),
        migrations.CreateModel(
            name='Litter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='идентификатор в легаси')),
                ('provenance', models.CharField(choices=[('imported', 'импортировано из легаси'), ('user', 'внесено пользователем'), ('verified', 'проверено по документам')], default='user', max_length=16, verbose_name='происхождение')),
                ('edited_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None, verbose_name='поля, правленные вручную')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('date_born', models.DateField(blank=True, null=True, verbose_name='дата рождения')),
                ('letter', models.CharField(blank=True, max_length=8, verbose_name='буква помёта')),
                ('dam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters_as_dam', to='pedigree.dog', verbose_name='мать')),
                ('kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters', to='pedigree.kennel', verbose_name='питомник')),
                ('sire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='litters_as_sire', to='pedigree.dog', verbose_name='отец')),
            ],
            options={
                'verbose_name': 'помёт',
                'verbose_name_plural': 'помёты',
                'ordering': ['-date_born'],
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='litter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puppies', to='pedigree.litter', verbose_name='помёт'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_id', models.IntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='идентификатор в легаси')),
                ('provenance', models.CharField(choices=[('imported', 'импортировано из легаси'), ('user', 'внесено пользователем'), ('verified', 'проверено по документам')], default='user', max_length=16, verbose_name='происхождение')),
                ('edited_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None, verbose_name='поля, правленные вручную')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('name', models.CharField(max_length=200, verbose_name='имя')),
                ('raw_name', models.TextField(blank=True, verbose_name='как записано в легаси')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='адрес')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedigree.country', verbose_name='страна')),
                ('kennel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='pedigree.kennel', verbose_name='питомник')),
            ],
            options={
                'verbose_name': 'человек',
                'verbose_name_plural': 'люди',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='breeder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bred_dogs', to='pedigree.person', verbose_name='заводчик'),
        ),
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_dogs', to='pedigree.person', verbose_name='владелец'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dogs/%Y/%m', verbose_name='файл')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='подпись')),
                ('is_primary', models.BooleanField(default=False, verbose_name='основное')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='порядок')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='pedigree.dog')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'фотографии',
                'ordering': ['-is_primary', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='аббревиатура')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='расшифровка')),
                ('kind', models.CharField(choices=[('show', 'выставочный'), ('field', 'полевые испытания'), ('other', 'прочий')], default='show', max_length=8, verbose_name='тип')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pedigree.country', verbose_name='страна')),
            ],
            options={
                'verbose_name': 'титул',
                'verbose_name_plural': 'титулы',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='DogTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='год')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dog_titles', to='pedigree.dog')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedigree.title')),
            ],
            options={
                'verbose_name': 'титул собаки',
                'verbose_name_plural': 'титулы собаки',
            },
        ),
        migrations.AddField(
            model_name='dog',
            name='titles',
            field=models.ManyToManyField(blank=True, related_name='dogs', through='pedigree.DogTitle', to='pedigree.title', verbose_name='титулы'),
        ),
        migrations.CreateModel(
            name='HealthTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('clear', 'чист'), ('carrier', 'носитель'), ('affected', 'поражён'), ('unknown', 'не тестирован')], default='unknown', max_length=10, verbose_name='результат')),
                ('genotype', models.CharField(blank=True, max_length=30, verbose_name='генотип')),
                ('lab', models.CharField(blank=True, max_length=120, verbose_name='лаборатория')),
                ('tested_on', models.DateField(blank=True, null=True, verbose_name='дата теста')),
                ('document', models.FileField(blank=True, upload_to='health/%Y/%m', verbose_name='документ')),
                ('verified', models.BooleanField(default=False, verbose_name='подтверждено по документу')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tests', to='pedigree.disease')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_tests', to='pedigree.dog')),
            ],
            options={
                'verbose_name': 'тест здоровья',
                'verbose_name_plural': 'тесты здоровья',
                'ordering': ['disease__name'],
                'constraints': [models.UniqueConstraint(fields=('dog', 'disease', 'tested_on'), name='uniq_dog_disease_date')],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100, verbose_name='организация')),
                ('number', models.CharField(db_index=True, max_length=100, verbose_name='номер')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='pedigree.dog')),
            ],
            options={
                'verbose_name': 'регистрация',
                'verbose_name_plural': 'регистрации',
                'constraints': [models.UniqueConstraint(fields=('dog', 'organisation', 'number'), name='uniq_dog_registration')],
            },
        ),
        migrations.AddConstraint(
            model_name='dogtitle',
            constraint=models.UniqueConstraint(fields=('dog', 'title'), name='uniq_dog_title'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['size', 'coat'], name='pedigree_do_size_3dabba_idx'),
        ),
        migrations.AddIndex(
            model_name='dog',
            index=models.Index(fields=['date_born'], name='pedigree_do_date_bo_aaa526_idx'),
        ),
    ]
